import Btn from "./Button";
import Md from "./Markdown";
import Crd from "./Card";
import NvBar from "./Navbar";
import Hmbger from "./Hamburger";
import Head from "./Header";
import Foot from "./Footer";
import Cols from "./Columns";
import Col from "./Column";
import Bx from "./Box";

export const Button = Btn;
export const Markdown = Md;
export const Card = Crd;
export const Navbar = NvBar;
export const Hamburger = Hmbger;
export const Header = Head;
export const Footer = Foot;
export const Columns = Cols;
export const Column = Col;
export const Box = Bx;
