import Btn from "./Button";
import Md from "./Markdown";
import Crd from "./Card";
import NvBar from "./Navbar";
import Hmbger from "./Hamburger";
import Head from "./Header";
import Foot from "./Footer";
import Cols from "./Columns";
import Col from "./Column";
import Bx from "./Box";
import Sc from "./Skills-Chart";
import Sum from "./Summary";
import SkS from "./Skills-Section";
import ArtActions from "./ArticleActions";

export const Button = Btn;
export const Markdown = Md;
export const Card = Crd;
export const Navbar = NvBar;
export const Hamburger = Hmbger;
export const Header = Head;
export const Footer = Foot;
export const Columns = Cols;
export const Column = Col;
export const Box = Bx;
export const SkillsChart = Sc;
export const Summary = Sum;
export const SkillsSection = SkS;
export const ArticleActions = ArtActions;
